### ISSUE TITLE
does iosrtc works with capacitor for you?

### ISSUE THREAD

**Issue by hthetiot** [phairow/pubnubchatrcionic#1]
does iosrtc works with capacitor for you?
See https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues/498#issuecomment-654143241

Your help and feedback would be appreciated.

**Comment by phairow** [comment]
It is working in the emulator but I cannot build for amd64 so far.

**Comment by phairow** [comment]
It is working now, thanks again for looking!
